# - pipeline.id: clickhouse-pipeline
#   path.config: "/usr/share/logstash/pipeline/clickhouse.conf"

- pipeline.id: orders
  path.config: "/usr/share/logstash/pipeline/orders.conf"

- pipeline.id: games
  path.config: "/usr/share/logstash/pipeline/games.conf"
